### DISCUSSION TITLE
Update Netro with Météo France weather data

### DISCUSSION THREAD

**Discussion by kcofoni** [kcofoni/ha-netro-watering#9] [Show and tell]
This post will be of interest mainly to users in France although it is perfectly applicable to any HA-integrated weather provider.

**IMPORTANT : Version 1.1.2 of the integration is required.**

### The idea is to feed Netro with relevant weather data and then get also relevant watering schedules.

To do that:

0. Have installed the Météo France integration and have enabled all entities (some are disabled by default) for the city where your Netro system operates
1. One script for updating Netro with the Météo France data, catched from Meteo France Integration entities and push to Netro using Netro Watering Report Weather service provided by Netro Watering integration (see below)
2. One automation for triggering twice a day the latter script (see the end of this post)

Warning: it's still very fresh even if some tests have been carried out successfully. Improvements will undoubtedly be made in the future.

_You may copy and paste the script code below and replace the values of the script variables (line 4 to 9) by your own entities_:

```python
alias: Netro Synchro Météo France
mode: single
icon: mdi:weather-sunny
variables:
  weather_entity: weather.royan
  rain_prob_entity: sensor.royan_rain_chance
sequence:
  - alias: report today weather in detail
    service: netro_watering.report_weather
    data:
      config_entry_id: "{{ config_entry_controller }}"
      date: >
        {{ as_timestamp(state_attr(weather_entity,'forecast')[0].datetime,
        now()) | timestamp_custom("%Y-%m-%d") }}
      condition: >
        {% set mapped_conditions = {'clear-night': 'clear', 'cloudy': 'cloudy',
        'exceptional': 'clear', 'fog': 'cloudy', 'hail': 'rain', 'lightning':
        'rain', 'lightning-rainy': 'rain', 'partlycloudy': 'cloudy', 'pouring':
        'rain', 'rainy': 'rain', 'snowy': 'snow', 'snowy-rainy': 'snow',
        'sunny': 'clear', 'windy': 'wind', 'windy-variant': 'wind'} %}

        {% set current_condition =
        state_attr(weather_entity,'forecast')[0].condition %}

        {{ mapped_conditions[current_condition] }}
      rain: |
        {{ state_attr(weather_entity,'forecast')[0].precipitation }}
      t_min: |
        {{ state_attr(weather_entity,'forecast')[0].templow }}
      t_max: |
        {{ state_attr(weather_entity,'forecast')[0].temperature }}
      rain_prob: |
        {{ states(rain_prob_entity) }}
      temp: |
        {{ state_attr(weather_entity,'temperature') }}
      wind_speed: |
        {{ (state_attr(weather_entity,'wind_speed') | float / 3.6) | round(1) }}
      pressure: |
        {{ state_attr(weather_entity,'pressure') }}
      humidity: |
        {{ state_attr(weather_entity,'humidity') }}
  - alias: report the next n days weather forecast
    repeat:
      count: "{{ number_of_days_forecast }}"
      sequence:
        - service: netro_watering.report_weather
          data:
            config_entry_id: "{{ config_entry_controller }}"
            date: >
              {{
              as_timestamp(state_attr(weather_entity,'forecast')[repeat.index].datetime,
              now()) | timestamp_custom("%Y-%m-%d") }}
            condition: >
              {% set mapped_conditions = {'clear-night': 'clear', 'cloudy':
              'cloudy', 'exceptional': 'clear', 'fog': 'cloudy', 'hail': 'rain',
              'lightning': 'rain', 'lightning-rainy': 'rain', 'partlycloudy':
              'cloudy', 'pouring': 'rain', 'rainy': 'rain', 'snowy': 'snow',
              'snowy-rainy': 'snow', 'sunny': 'clear', 'windy': 'wind',
              'windy-variant': 'wind'} %}

              {% set current_condition =
              state_attr(weather_entity,'forecast')[repeat.index].condition %}

              {{ mapped_conditions[current_condition] }}
            rain: >
              {{
              state_attr(weather_entity,'forecast')[repeat.index].precipitation
              }}
            t_min: |
              {{ state_attr(weather_entity,'forecast')[repeat.index].templow }}
            t_max: >
              {{ state_attr(weather_entity,'forecast')[repeat.index].temperature
              }}


``` 
_This is the very simple automation related_:

```python
alias: Synchro Netro Météo France
description: Mise à jour de Netro avec les données de Météo France 3x/jour
trigger:
  - platform: time
    at: "02:00:00"
  - platform: time
    at: "11:00:00"
  - platform: time
    at: "20:00:00"
condition:
  - condition: device
    type: is_on
    device_id: bdcb5b8eda38d985a3f4c602959ec86a
    entity_id: switch.watering_controller_enable_disable
    domain: switch
action:
  - alias: >-
      synchro sur l'id de configuration du contrôleur et sur un certain nombre
      de jours de prévision
    service: script.netro_synchro_meteo_france
    data:
      config_entry_controller: 2c149e757d07ad1411abe98d546490a2
      number_of_days_forecast: 2
      weather_location: royan
  - service: persistent_notification.create
    data:
      message: Les données de Météo France ont été transmises à Netro
      title: "Netro : Synchro Météo effectuée"
mode: single

``` 
config_entry_controller to be changed with your controller id and weather_country by the name of the weather entity you have created with Météo France integration.

**Comment by amery78** [comment]
Hello, thank you for the integration and the share !!
Despite my efforts, I was not able to make it work (French weather data). Could you help me ?
thank you !!
Axel

**Reply by kcofoni** [reply]
Hi, did you create the script and automation successfully ? What kind of issue do you encounter ?

**Reply by amery78** [reply]
Hello, thank you for your answer, when I try to launch the script I have this message : 
"Échec de l'exécution de l'action script/netro_synchro_meteo_france. Error rendering data template: UndefinedError: None has no element 0"

here is the script used : 

```typescript
alias: Netro Synchro Météo France
mode: single
icon: mdi:weather-sunny
variables:
  weather_entity: weather.montreuil
  rain_prob_entity: sensor.montreuil_cloud_cover_rain_chance
  temperature_entity: sensor.montreuil_temperature
  wind_speed_entity: sensor.montreuil_wind_speed
  pressure_entity: sensor.montreuil_pressure
sequence:
  - alias: report today weather in detail
    data:
      config_entry_id: "{{ config_entry_controller }}"
      date: >
        {{ as_timestamp(state_attr(weather_entity,'forecast')[0].datetime,
        now()) | timestamp_custom("%Y-%m-%d") }}
      condition: >
        {% set mapped_conditions = {'clear-night': 'clear', 'cloudy': 'cloudy',
        'exceptional': 'clear', 'fog': 'cloudy', 'hail': 'rain', 'lightning':
        'rain', 'lightning-rainy': 'rain', 'partlycloudy': 'cloudy', 'pouring':
        'rain', 'rainy': 'rain', 'snowy': 'snow', 'snowy-rainy': 'snow',
        'sunny': 'clear', 'windy': 'wind', 'windy-variant': 'wind'} %}

        {% set current_condition =
        state_attr(weather_entity,'forecast')[0].condition %}

        {{ mapped_conditions[current_condition] }}
      rain: |
        {{ state_attr(weather_entity,'forecast')[0].precipitation }}
      t_min: |
        {{ state_attr(weather_entity,'forecast')[0].templow }}
      t_max: |
        {{ state_attr(weather_entity,'forecast')[0].temperature }}
      rain_prob: |
        {{ states(rain_prob_entity) }}
      temp: |
        {{ state_attr(weather_entity,'temperature') }}
      wind_speed: |
        {{ (state_attr(weather_entity,'wind_speed') | float / 3.6) | round(1) }}
      pressure: |
        {{ state_attr(weather_entity,'pressure') }}
      humidity: |
        {{ state_attr(weather_entity,'humidity') }}
    action: netro_watering.report_weather
  - alias: report the next n days weather forecast
    repeat:
      count: "{{ number_of_days_forecast }}"
      sequence:
        - data:
            config_entry_id: "{{ config_entry_controller }}"
            date: >
              {{
              as_timestamp(state_attr(weather_entity,'forecast')[repeat.index].datetime,
              now()) | timestamp_custom("%Y-%m-%d") }}
            condition: >
              {% set mapped_conditions = {'clear-night': 'clear', 'cloudy':
              'cloudy', 'exceptional': 'clear', 'fog': 'cloudy', 'hail': 'rain',
              'lightning': 'rain', 'lightning-rainy': 'rain', 'partlycloudy':
              'cloudy', 'pouring': 'rain', 'rainy': 'rain', 'snowy': 'snow',
              'snowy-rainy': 'snow', 'sunny': 'clear', 'windy': 'wind',
              'windy-variant': 'wind'} %}

              {% set current_condition =
              state_attr(weather_entity,'forecast')[repeat.index].condition %}

              {{ mapped_conditions[current_condition] }}
            rain: >
              {{
              state_attr(weather_entity,'forecast')[repeat.index].precipitation
              }}
            t_min: |
              {{ state_attr(weather_entity,'forecast')[repeat.index].templow }}
            t_max: >
              {{ state_attr(weather_entity,'forecast')[repeat.index].temperature
              }}
          action: netro_watering.report_weather

``` 

thanks in advance for your help :)

**Reply by amery78** [reply]
Hello, any idea @kcofoni ? 😇
Any help would be really appreciated ;)

Thank you :)

**Reply by kcofoni** [reply]
Hi amery,

I am going to investigate in order to properly help you to fix this issue. I have a very good news, I can reproduce !
So, I come back to you very soon  :wink:

**Reply by kcofoni** [reply]
Since late-2024, most weather integrations (incl. Météo-France) stopped populating the forecast attribute directly on the weather.* entity. You now need to call weather.get_forecasts and read the result, or defensively handle a missing list.

Please try this. It seems to work on my side. I did not analyze deeply yet but in the meantime...

```yaml
alias: Netro Synchro Météo France
mode: single
icon: mdi:weather-sunny
variables:
  weather_entity: weather.royan
  rain_prob_entity: sensor.royan_rain_chance
  number_of_days_forecast: "{{ number_of_days_forecast | default(3) }}"
sequence:
  - alias: Fetch daily forecast
    action: weather.get_forecasts
    target:
      entity_id: "{{ weather_entity }}"
    data:
      type: daily
    response_variable: forecast_daily
  - variables:
      fc: >-
        {{ forecast_daily.get(weather_entity).forecast if
        forecast_daily.get(weather_entity) else [] }}
      mapped_conditions: |
        {{ {
          'clear-night': 'clear', 'cloudy': 'cloudy', 'exceptional': 'clear',
          'fog': 'cloudy', 'hail': 'rain', 'lightning': 'rain',
          'lightning-rainy': 'rain', 'partlycloudy': 'cloudy', 'pouring': 'rain',
          'rainy': 'rain', 'snowy': 'snow', 'snowy-rainy': 'snow',
          'sunny': 'clear', 'windy': 'wind', 'windy-variant': 'wind'
        } }}
  - alias: report today weather in detail
    action: netro_watering.report_weather
    data:
      config_entry_id: "{{ config_entry_controller }}"
      date: |
        {{
          (as_timestamp(fc[0].datetime, now()) if fc|count > 0 else as_timestamp(now()))
          | timestamp_custom("%Y-%m-%d")
        }}
      condition: >
        {% set raw = (fc[0].condition if fc|count > 0 else
        state_attr(weather_entity,'condition') or 'clear') %} {{
        mapped_conditions.get(raw, 'clear') }}
      rain: |
        {{ (fc[0].precipitation if fc|count > 0 else 0) }}
      t_min: >
        {{ (fc[0].templow if fc|count > 0 else
        state_attr(weather_entity,'temperature')) }}
      t_max: >
        {{ (fc[0].temperature if fc|count > 0 else
        state_attr(weather_entity,'temperature')) }}
      rain_prob: |
        {{ states(rain_prob_entity) }}
      temp: |
        {{ state_attr(weather_entity,'temperature') }}
      wind_speed: >
        {{ ((state_attr(weather_entity,'wind_speed') | float / 3.6) | round(1))
        }}
      pressure: |
        {{ state_attr(weather_entity,'pressure') }}
      humidity: |
        {{ state_attr(weather_entity,'humidity') }}
  - alias: report the next n days weather forecast
    repeat:
      count: "{{ number_of_days_forecast }}"
      sequence:
        - variables:
            i: "{{ repeat.index }}"
            day: "{{ fc[i] if fc|count > i else none }}"
        - condition: template
          value_template: "{{ day is not none }}"
        - action: netro_watering.report_weather
          data:
            config_entry_id: "{{ config_entry_controller }}"
            date: >
              {{ as_timestamp(day.datetime, now()) |
              timestamp_custom("%Y-%m-%d") }}
            condition: >
              {% set raw = day.condition %} {{ mapped_conditions.get(raw,
              'clear') }}
            rain: |
              {{ day.precipitation | default(0) }}
            t_min: >
              {{ day.templow | default(state_attr(weather_entity,'temperature'))
              }}
            t_max: >
              {{ day.temperature |
              default(state_attr(weather_entity,'temperature')) }}
```
