### ISSUE TITLE
Ability to set run time per station

### ISSUE THREAD

**Issue by dasviridov** [kcofoni/ha-netro-watering#14]
Hi,

First of all, thank you for implementing this integration!

I wonder if it's possible to implement duration of manual run as an input_number for each station. So I can set them individually instead of global setting for all stations. That way I can do a card like this:
![vivaldi_88GErFrRyt](https://github.com/kcofoni/ha-netro-watering/assets/15569157/1dc9ac04-afb6-4f1e-a7c4-aad103d2e85a)

Otherwise please provide a service to call with zone number and duration.

Thanks a lot.

**Comment by kcofoni** [comment]
Hi, 

As indicated in the documentation, a service is available for manual irrigation of a given zone

```
start_watering:
  name: Start watering
  description: Start watering for a specified duration, delay before start, or start time and date
  target:
    entity:
      integration: netro_watering
      domain: switch
  fields:
    duration:
      name: Duration
      description: Duration of activation of this sprinkler
      required: true
      default: 30
      selector:
        number:
          min: 1
          max: 90
          unit_of_measurement: "minutes"
    delay:
      name: Delay
      description: Waiting time before starting watering
      required: false
      selector:
        number:
          min: 0
          max: 90
          unit_of_measurement: "minutes"
    start_time:
      name: Start time
      description: Watering start date and time
      required: false
      selector:
        datetime:

```
<img width="1091" alt="image" src="https://github.com/kcofoni/ha-netro-watering/assets/75487677/45084d80-9439-4fbc-8298-9a8dcac8830b">

Hope this helps !
